# Generated by Django 5.1.7 on 2025-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('AI/ML', 'AI & Machine Learning'), ('NLP', 'NLP & Generative AI'), ('MLOps', 'MLOps & Cloud'), ('Backend Technologies', 'Backend Frameworks')], default='AI/ML', max_length=50),
        ),
    ]
