# Generated by Django 5.1.7 on 2025-04-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_options_remove_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
    ]
