# Generated by Django 5.1.7 on 2025-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_userprofile_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='copyright_text',
            field=models.CharField(max_length=200),
        ),
    ]
