# Generated by Django 5.1.7 on 2025-04-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_siteconfiguration_copyright_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='copyright_text',
        ),
    ]
