# Generated by Django 5.1.7 on 2025-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_siteconfiguration_copyright_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-current', '-end_date', '-start_date']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('AI/ML', 'Machine Learning & Data Analysis'), ('NLP', 'NLP & Generative AI'), ('MLOps', 'Data Engineering & Cloud Computing'), ('Backend Technologies', 'Backend Frameworks')], default='AI/ML', max_length=50),
        ),
    ]
